// This file will be generated by `flutterfire configure`.
// Keeping here as a placeholder so imports compile until you configure Firebase.
class DefaultFirebaseOptions {
  static dynamic get currentPlatform => null;
}
